title: Companion website for the paper "On the Nature of Software Merge Conflicts"
description: This website hosts raw data for an analysis on the nature of software merge conflicts.
theme: jekyll-theme-tactile
