/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.ic.github.mergeviewer;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author Gleiph
 */
public class ShowFiles extends javax.swing.JFrame {

    String originalContent;
    String head1Content;
    String head2Content;
    String mergeContent;
    String developerContent;

    /**
     * Creates new form ShowFiles
     */
    public ShowFiles() {
        initComponents();
    }

    public ShowFiles(String pathOriginal, String pathHead1, String pathHead2, String pathMerge, String pathDeveloper) {
        initComponents();

        try {
            originalContent = FileUtils.readFileToString(new File(pathOriginal));
            head1Content = FileUtils.readFileToString(new File(pathHead1));
            head2Content = FileUtils.readFileToString(new File(pathHead2));
            mergeContent = FileUtils.readFileToString(new File(pathMerge));
            developerContent = FileUtils.readFileToString(new File(pathDeveloper));
            
            jtOriginal.setText(originalContent);
            jtHead1.setText(head1Content);
            jtHead2.setText(head2Content);
            jtMerge.setText(mergeContent);
            jtRealMerge.setText(developerContent);
            
        } catch (IOException ex) {
            Logger.getLogger(ShowFiles.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtOriginal = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtHead1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtHead2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtMerge = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtRealMerge = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtOriginal.setColumns(20);
        jtOriginal.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jtOriginal.setRows(5);
        jScrollPane1.setViewportView(jtOriginal);

        jtHead1.setColumns(20);
        jtHead1.setRows(5);
        jScrollPane2.setViewportView(jtHead1);

        jtHead2.setColumns(20);
        jtHead2.setRows(5);
        jScrollPane3.setViewportView(jtHead2);

        jtMerge.setColumns(20);
        jtMerge.setRows(5);
        jScrollPane4.setViewportView(jtMerge);

        jtRealMerge.setColumns(20);
        jtRealMerge.setRows(5);
        jScrollPane5.setViewportView(jtRealMerge);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
            .addComponent(jScrollPane4)
            .addComponent(jScrollPane5)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jtHead1;
    private javax.swing.JTextArea jtHead2;
    private javax.swing.JTextArea jtMerge;
    private javax.swing.JTextArea jtOriginal;
    private javax.swing.JTextArea jtRealMerge;
    // End of variables declaration//GEN-END:variables
}
