/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.ic.github.mergeviewer;

import br.uff.ic.github.mergeviewer.util.DeveloperChioce;
import br.uff.ic.github.mergeviewer.util.DeveloperDecision;
import java.awt.Dimension;
import java.util.List;

/**
 *
 * @author gleiph
 */
public class ShowCase extends javax.swing.JFrame {

    /**
     * Creates new form ShowCase
     */
    public ShowCase() {
        initComponents();
    }

    public ShowCase(List<String> conflict, List<String> solution, String dd, String ss) {
        initComponents();

        String conflicText = "";
        String solutionText = "";

        for (String line : solution) {
            solutionText += line + "\n";
        }

        for (String line : conflict) {
            conflicText += line + "\n";
        }

        jtConflict.setText(conflicText);
        jtSolution.setText(solutionText);
        
        jlDeveloperDecision.setText(dd);
        jlSyncaticStructures.setText(ss);
        
        DeveloperChioce developerDecision = DeveloperDecision.getDeveloperDecision(conflict, solution);
        jlDeveloperDecision.setText(developerDecision.toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jtSolution = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConflict = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlDeveloperDecision = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlSyncaticStructures = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                formAncestorResized(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jtSolution.setColumns(20);
        jtSolution.setRows(5);
        jScrollPane2.setViewportView(jtSolution);

        jtConflict.setColumns(20);
        jtConflict.setRows(5);
        jScrollPane1.setViewportView(jtConflict);

        jLabel1.setText("Developer's decision:");

        jlDeveloperDecision.setText("jLabel2");

        jLabel2.setText("Syntactic structures:");

        jlSyncaticStructures.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlDeveloperDecision, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlSyncaticStructures, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlDeveloperDecision)
                    .addComponent(jLabel2)
                    .addComponent(jlSyncaticStructures))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
//        Dimension frameDimension = this.getSize();
//        jPanel1.setSize(frameDimension);
//
//        double width = frameDimension.getWidth();
//        double height = frameDimension.getHeight();
//
//        Dimension d = new Dimension((int) width, (int) height / 2);
//
//        jtConflict.setSize(d);
//
//        jtSolution.setSize(d);

    }//GEN-LAST:event_formComponentResized

    private void formAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorResized
        // TODO add your handling code here:
        Dimension frameDimension = this.getSize();

        double width = frameDimension.getWidth();
        double height = frameDimension.getHeight();

        Dimension d = new Dimension((int) width, (int) height / 2);

        jtConflict.setSize(d);
        jtConflict.setAlignmentX(0);
        jtConflict.setAlignmentY(0);

        jtSolution.setSize(d);
        jtSolution.setAlignmentX(0);
        jtSolution.setAlignmentY((int)height/2);
        
    }//GEN-LAST:event_formAncestorResized

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlDeveloperDecision;
    private javax.swing.JLabel jlSyncaticStructures;
    private javax.swing.JTextArea jtConflict;
    private javax.swing.JTextArea jtSolution;
    // End of variables declaration//GEN-END:variables
}
